//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DbFirst_2
{
    using System;
    
    public enum DersTipi : byte
    {
        Sayısal = 0,
        Sözel = 1,
        Yetenek = 2,
        EsitAğırlık = 3,
        Dil = 4
    }
}
